"""add total_room_feedback_views_column

Revision ID: 5e09fc587903
Revises: d2a4ba0089fa
Create Date: 2019-01-17 20:10:42.427419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e09fc587903'
down_revision = 'd2a4ba0089fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('total_room_feedback_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'total_room_feedback_views')
    # ### end Alembic commands ###
